POLLS_RELEASE_SEED= -1586567995
POLLS_TESTING_SEED= -1077669241
AUTHOR_ID  = CROMU
SERVICE_ID = 00022
CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
