POLLS_RELEASE_SEED= -1778606513
AUTHOR_ID  = KPRCA
SERVICE_ID = 00001
CFLAGS     = -Os -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_TESTING_SEED = 1763254697

include /usr/share/cb-testing/cgc-cb.mk
