AUTHOR_ID  = KPRCA
SERVICE_ID = 00097
CFLAGS     = -O3 -g -Werror -Wall -Wold-style-cast
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
