POLLS_TESTING_SEED= -839347834
AUTHOR_ID  = KPRCA
SERVICE_ID = 00026
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -DFILAMENTS
POLLS_RELEASE_SEED = 1637181811

include /usr/share/cb-testing/cgc-cb.mk
