POLLS_RELEASE_SEED= -1197662839
POLLS_TESTING_SEED= -2119542976
AUTHOR_ID  = CROMU
SERVICE_ID = 00025
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
