AUTHOR_ID	= TNETS
SERVICE_ID	= 00002
CXXFLAGS	= -fno-exceptions -fno-rtti
CFLAGS     	= -O0 -g -Wall -fno-exceptions -fno-rtti

POLLS_RELEASE_SEED=0
POLLS_TESTING_COUNT=0

include /usr/share/cb-testing/cgc-cb.mk
