POLLS_RELEASE_SEED= -348354587
POLLS_TESTING_SEED= -1304034264
AUTHOR_ID  = NRFIN
SERVICE_ID = 00011
CFLAGS     = -g -O0 -Werror -Wno-overlength-strings -Wno-packed -Wno-array-bounds

include /usr/share/cb-testing/cgc-cb.mk
