AUTHOR_ID  = KPRCA
SERVICE_ID = 00112
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wno-narrowing -Wall 
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
