POLLS_RELEASE_SEED= -1456763818
POLLS_TESTING_SEED= 2143475288
AUTHOR_ID  = NRFIN
SERVICE_ID = 00004
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
