AUTHOR_ID  = KPRCA
SERVICE_ID = 00077
CFLAGS     = -Ofast -g -Werror -Wall
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1


include /usr/share/cb-testing/cgc-cb.mk
