POLLS_RELEASE_SEED= 128230504
POLLS_TESTING_SEED= -135449884
AUTHOR_ID  = CROMU
SERVICE_ID = 00032
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
