POLLS_RELEASE_SEED= -1967816728
POLLS_TESTING_SEED= 1458854663
AUTHOR_ID  = NRFIN
SERVICE_ID = 00014
POLLS_RELEASE_MAX_DEPTH = 750

CFLAGS = -Wno-overlength-strings -Wno-packed -Wno-trigraphs -Wno-switch -g

include /usr/share/cb-testing/cgc-cb.mk
