POLLS_RELEASE_SEED= -1623226171
POLLS_TESTING_SEED= -1632727288
AUTHOR_ID  = NRFIN
SERVICE_ID = 00032
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_COUNT = 1
POLLS_TESTING_COUNT = 1000

include /usr/share/cb-testing/cgc-cb.mk
