POLLS_TESTING_SEED= 594341358
AUTHOR_ID  = KPRCA
SERVICE_ID = 00023
CFLAGS     = -O1 -g -Werror -Wno-unused-function -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -514292027

include /usr/share/cb-testing/cgc-cb.mk
