POLLS_TESTING_SEED= 1460658953
AUTHOR_ID = KPRCA
SERVICE_ID = 00049
CFLAGS = -g -O3 -Werror -Wall -Wno-unused-function -Wno-unused-variable
POLLS_RELEASE_SEED = 092385883

include /usr/share/cb-testing/cgc-cb.mk
