AUTHOR_ID  = KPRCA
SERVICE_ID = 00055
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed -Wall -Wno-unused-variable -Wno-unused-function -Werror
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
