POLLS_RELEASE_SEED= -485651521
POLLS_TESTING_SEED= -334899908
AUTHOR_ID  = NRFIN
SERVICE_ID = 00025
CFLAGS     = -g -O0 -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
