POLLS_TESTING_SEED= 1430640505
AUTHOR_ID  = KPRCA
SERVICE_ID = 00036
CFLAGS     = -O -g -Wall -Wno-unused-function -Wno-unused-variable
POLLS_RELEASE_SEED = 1900525947

include /usr/share/cb-testing/cgc-cb.mk
