POLLS_RELEASE_SEED= 709726933
AUTHOR_ID  = KPRCA
SERVICE_ID = 00003
CFLAGS     = -Ofast -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_TESTING_SEED=349507159

include /usr/share/cb-testing/cgc-cb.mk
