POLLS_RELEASE_SEED= -464241766
POLLS_TESTING_SEED= 910797371
AUTHOR_ID  = NRFIN
SERVICE_ID = 00012
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed
NO_STRIP = 1
POLLS_TESTING_COUNT = 1000
POLLS_RELEASE_COUNT = 100

include /usr/share/cb-testing/cgc-cb.mk
