POLLS_TESTING_SEED= -81977984
AUTHOR_ID  = KPRCA
SERVICE_ID = 00053
TCP_PORT   = 10010
CXXFLAGS   = -fno-exceptions -fno-rtti
CFLAGS     = -O0 -g -Wall -fno-exceptions -fno-rtti
POLLS_RELEASE_SEED = 1900525947

include /usr/share/cb-testing/cgc-cb.mk
