POLLS_RELEASE_SEED= 2130245018
POLLS_TESTING_SEED= 1738410521
AUTHOR_ID  = CROMU
SERVICE_ID = 00008

CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
