#!/usr/bin/python

"""
CB Testing tool

Copyright (C) 2014 - Brian Caswell <bmc@lungetech.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

This tool validates an XML against the replay DTD.
"""

import lxml.etree
import sys

errors = False

dtd_path = '/usr/share/cgc-docs/replay.dtd'
xml_line = '<?xml version="1.0" standalone="no" ?>'
dtd_line = '<!DOCTYPE pov SYSTEM "%s">' % dtd_path

def error(filename, message):
    sys.stderr.write("ERROR %s: %s\n" % (filename, message))
    errors = True

with open(dtd_path, 'r') as fh:
    dtd = lxml.etree.DTD(fh)

for filename in sys.argv[1:]:
    xml = ''
    with open(filename, 'r') as fh:
        xml = fh.read()
   
    if not xml.startswith(xml_line):
        error(filename, "does not start with 'xml' tag.  Expecting: %s"  % xml_line)
   
    try:  
        root = lxml.etree.XML(xml)
    except lxml.etree.XMLSyntaxError as err:
        error(filename, "parse error: %s" % str(err))
    
    if root.getroottree().docinfo.doctype != dtd_line:
        error(filename, "invalid DOCTYPE.  Expecting: %s" % dtd_line)

    if not dtd.validate(root):
        for parse_error in dtd.error_log:
            error(filename, "parse error (line %d): %s" % (parse_error.line, parse_error.message))

if errors:
    sys.exit(-1)
