AUTHOR_ID  = KPRCA
SERVICE_ID = 00068
CFLAGS     = -O3 -mstackrealign -g -Werror -Wno-overlength-strings -Wno-packed -Wall
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1
POLLS_RELEASE_MAX_DEPTH = 2000

include /usr/share/cb-testing/cgc-cb.mk
