POLLS_RELEASE_SEED= 1540773688
POLLS_TESTING_SEED= -1867784253
AUTHOR_ID  = NRFIN
SERVICE_ID = 00020
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
