POLLS_RELEASE_SEED= -1487549617
POLLS_TESTING_SEED= -2018907573
AUTHOR_ID  = NRFIN
SERVICE_ID = 00013
POLLS_RELEASE_COUNT = 200
POLLS_TESTING_COUNT = 800

CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
