POLLS_RELEASE_SEED= 1869822527
POLLS_TESTING_SEED= -1848714694
AUTHOR_ID  = CROMU
SERVICE_ID = 00030
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
