POLLS_RELEASE_SEED= 1541717652
POLLS_TESTING_SEED= 414357196
AUTHOR_ID  = NRFIN
SERVICE_ID = 00036
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
