POLLS_RELEASE_SEED= -1016190807
POLLS_TESTING_SEED= -234231801
AUTHOR_ID  = NRFIN
SERVICE_ID = 00040
CFLAGS     = -g -O0 -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
