AUTHOR_ID  = CROMU
SERVICE_ID = 00015
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED=594936938
POLLS_TESTING_SEED=-1420921681

include /usr/share/cb-testing/cgc-cb.mk
