POLLS_TESTING_SEED= -953380193
AUTHOR_ID  = KPRCA
SERVICE_ID = 00043
CFLAGS     = -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 1751193365

include /usr/share/cb-testing/cgc-cb.mk
