POLLS_RELEASE_SEED= 1578966870
POLLS_TESTING_SEED= -1104170671
AUTHOR_ID  = NRFIN
SERVICE_ID = 00035
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
