AUTHOR_ID  = CROMU
SERVICE_ID = 00029
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED=-773946578
POLLS_TESTING_SEED=-1906672637

include /usr/share/cb-testing/cgc-cb.mk
