#ifndef __NAMES_H__
#define __NAMES_H__

char *names[] = {"Lost Needless Duck",  
				 "The Commander", 
				 "Toxic Major",
				 "El Spider",
				 "The Heroic Emperor",
				 "Rock Beast",
				 "Gamma Guardian",
				 "Rough Wizard",
				 "Persistent Puppet",
				 "Pure Ghost Killer",
				 "The Golden Oyster",
				 "Hidden Leather",
				 "Dreaded Digital Hawk",
				 "The Admiral",
				 "Sneaky Tough Electron",
				 "Trolling Captain",
				 "The Barbarian",
				 "Elvish Moose",
				 "Snappy Dinosaur",
				 "The Bursting Wrench",
				 "Itchy Eagle",
				 "Angry Neutron",
				 "Asada Gothar Derik",
				 "Seth Bydern",
				 "Quid Cipyar",
				 "Amarisa Yerpal Jihb",
				 "Tilthan",
				 "Teressa Gosform",
				 "Uerth Bredock Lidorn",
				 "Raydan Fronar",
				 "Aldaren Cevelt",
				 "Florian",
				 "Celestine Ixil Boldel",
				 "Safize Ixen",
				 "Corda Migorn",
				 "Vigoth Boldel",
				 "Gothar Mathar",
				 "Vinkol Seryth",
				 "Wrathran Palpur",
				 "Luna Milen",
				 "Zotar Phalloz",
				 "Pildoor Vildar Virdo",
				 "Odeir Jibar Wyeth",
				 "Fearlock Breen",
				 "Soderman Iroldak",
				 "Lelani Oxpar Xavor",
				 NULL
				};


#endif

