POLLS_RELEASE_SEED= -1229701906
POLLS_TESTING_SEED= 724675058
AUTHOR_ID  = NRFIN
SERVICE_ID = 00003
CFLAGS     = -g -O0 -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
