POLLS_RELEASE_SEED= 1681795162
POLLS_TESTING_SEED= 1677617456
AUTHOR_ID  = NRFIN
SERVICE_ID = 00016
CFLAGS     = -mno-sse -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_COUNT = 1000

include /usr/share/cb-testing/cgc-cb.mk
