POLLS_RELEASE_SEED= 1381088693
POLLS_TESTING_SEED= 2104697472
AUTHOR_ID  = CROMU
SERVICE_ID = 00001
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
