POLLS_RELEASE_SEED= 1351646732
POLLS_TESTING_SEED= -740999963
AUTHOR_ID  = NRFIN
SERVICE_ID = 00033
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
