POLLS_TESTING_SEED= -1680036876
AUTHOR_ID  = KPRCA
SERVICE_ID = 00033
CFLAGS     = -O -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 1980600223

include /usr/share/cb-testing/cgc-cb.mk
