POLLS_RELEASE_SEED= 35476131
POLLS_TESTING_SEED= -634785393
AUTHOR_ID  = NRFIN
SERVICE_ID = 00026
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_COUNT = 1
POLLS_TESTING_COUNT = 1000

include /usr/share/cb-testing/cgc-cb.mk
