POLLS_RELEASE_SEED= -1944510988
POLLS_TESTING_SEED= -1711771373
AUTHOR_ID  = NRFIN
SERVICE_ID = 00024
CFLAGS     = -O0 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_COUNT = 1000
POLLS_TESTING_COUNT = 1000

include /usr/share/cb-testing/cgc-cb.mk
