POLLS_TESTING_SEED= 871019178
AUTHOR_ID  = KPRCA
SERVICE_ID = 00014
CFLAGS     = -Os -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 86421966

include /usr/share/cb-testing/cgc-cb.mk
