AUTHOR_ID  = KPRCA
SERVICE_ID = 00100
CFLAGS     = -O2 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -Wno-delete-non-virtual-dtor
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
