AUTHOR_ID  = KPRCA
SERVICE_ID = 00075
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -DDISABLE_HEAP_GUARD
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
