AUTHOR_ID  = KPRCA
SERVICE_ID = 00094
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -DPRINTF_CHAR=59
VULN_COUNT = 1
POLLS_RELEASE_MAX_DEPTH = 1500

include /usr/share/cb-testing/cgc-cb.mk
