POLLS_RELEASE_SEED= 2100533457
POLLS_TESTING_SEED= -860155297
AUTHOR_ID  = NRFIN
SERVICE_ID = 00038
CFLAGS     = -O0 -g -Wall -Wextra -Wno-overlength-strings -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-function

include /usr/share/cb-testing/cgc-cb.mk
