POLLS_RELEASE_SEED= -1116284956
POLLS_TESTING_SEED= 1724357878
AUTHOR_ID  = NRFIN
SERVICE_ID = 00042
CFLAGS     = -O3 -g -fcommon -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_COUNT = 1000
POLLS_TESTING_COUNT = 1000

include /usr/share/cb-testing/cgc-cb.mk
