POLLS_RELEASE_SEED= 1374336218
POLLS_TESTING_SEED= 1103748769
AUTHOR_ID  = CROMU
SERVICE_ID = 00018
POLLS_TESTING_COUNT = 1000

CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
