POLLS_RELEASE_SEED= -460875359
POLLS_TESTING_SEED= 1788942791
AUTHOR_ID  = KPRCA
SERVICE_ID = 00015
CFLAGS     = -Os -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
