AUTHOR_ID  = NRFIN
SERVICE_ID = 00017
POLLS_RELEASE_COUNT = 1000
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = 854437448
POLLS_TESTING_SEED = 1892282553

include /usr/share/cb-testing/cgc-cb.mk
