POLLS_RELEASE_SEED= -2005941541
POLLS_TESTING_SEED= -134988288
AUTHOR_ID  = CROMU
SERVICE_ID = 00041
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
