POLLS_RELEASE_SEED= -1679470181
POLLS_TESTING_SEED= 2008189601
AUTHOR_ID  = CROMU
SERVICE_ID = 00031
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
