POLLS_RELEASE_SEED= -659348995
POLLS_TESTING_SEED= 1662257982
AUTHOR_ID  = NRFIN
SERVICE_ID = 00037
CFLAGS     = -g -O0 -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
