POLLS_TESTING_SEED= 243457283
AUTHOR_ID = KPRCA
SERVICE_ID = 00035
CFLAGS = -O0 -Werror -Wall -Wno-unused-function -Wno-unused -Wno-compare-distinct-pointer-types -Wno-sometimes-uninitialized
POLLS_RELEASE_SEED = -868333550

include /usr/share/cb-testing/cgc-cb.mk
