POLLS_RELEASE_SEED= -949143514
POLLS_TESTING_SEED= 355624858
AUTHOR_ID  = CROMU
SERVICE_ID = 00035
CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
