POLLS_TESTING_SEED= 626884884
AUTHOR_ID  = KPRCA
SERVICE_ID = 00016
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -1113420046

include /usr/share/cb-testing/cgc-cb.mk
