POLLS_TESTING_SEED= -1038971563
AUTHOR_ID = KPRCA
SERVICE_ID = 00039
CFLAGS = -g -Ofast -Werror -Wall -Wno-unused-function -Wno-unused -Wno-compare-distinct-pointer-types -Wno-sometimes-uninitialized -fshort-enums
POLLS_RELEASE_SEED = -868333550
POLLS_RELEASE_COUNT = 0

include /usr/share/cb-testing/cgc-cb.mk
