POLLS_TESTING_SEED= -2031454471
AUTHOR_ID  = KPRCA
SERVICE_ID = 00045
CFLAGS     = -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 2930732202

include /usr/share/cb-testing/cgc-cb.mk
