POLLS_RELEASE_SEED= -389955366
POLLS_TESTING_SEED= 1409750963
AUTHOR_ID  = YAN01
SERVICE_ID = 00009
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
