//#The following is a list of quotes from the American Film Institute's 100 Years... 100 Movie Quotes. The quotes were retrieved from Wikipedia <http://en.wikipedia.org/wiki/AFI's_100_Years...100_Movie_Quotes>. A few truncations were made so the sentences fit into 64 characters. Also we only used the first 50 quotes in reverse chronological order.

char* gSeedWords[] = {
"My precious.",
"I see dead people.",
"I'm the kind of the world!",
"Show me the money!",
"You had me at hello.",
"Houston, we have a problem.",
"Mama always said life was like a box of chocolates.",
"You can't handle the truth!",
"There's no crying in baseball!",
"A census taker once tried to test me.",
"Hasta la vista, baby.",
"I'll have what she's having.",
"If you build it, he will come.",
"Carpe diem. Seize the day, boys.",
"Greed, for lack of a better word, is good.",
"Snap out of it!",
"Nobody puts Baby in a corner.",
"I feel the need-the need for speed!",
"I'll be back.",
"Go ahead, make my day.",
"Say hello to my little friend!",
"E.T. phone home.",
"They're here!",
"No wire hangers, ever!",
"Listen to me, mister. You're my knight in shining armor.",
"Here's Johnny!",
"I am serious...and don't call me Shirley.",
"Cinderella story. Outta nowhere.",
"I love the smell of napalm in the morning.",
"Toga! Toga!",
"May the Force be with you.",
"La-dee-da, la-dee-da.",
"You talkin' to me?",
"I'm as mad as hell, and I'm not going to take this anymore!",
"Is it safe?",
"Yo, Adrian!",
"You're gonna need a bigger boat.",
"Attica! Attica!",
"Keep your friends close, but your enemies closer.",
"Forget it, Jake, it's Chinatown.",
"Soylent Green is people!",
"I'm going to make him an offer he can't refuse.",
"You've got to ask yourself one question: 'Do I feel lucky?'",
"Love means never having to say you're sorry",
"I'm walking here! I'am walking here!",
"Get your stinking paws off me, you damned dirty ape.",
"Open the pod bay doors please, HAL.",
"Hello, gorgeous.",
"What we've got here is failure to communicate.",
"They call me Mister Tibbs!",
"We rob banks.",
};
