AUTHOR_ID  = KPRCA
SERVICE_ID = 00058
CFLAGS     = -O1 -fomit-frame-pointer -g -Wall -Werror -Wno-overlength-strings -Wno-packed -Wno-unused-variable -Wno-unused-function
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
