#!/usr/bin/env python
#
# Copyright (C) # 2013 Legitimate Business Syndicate <https://legitbs.net/>
# 
# License: CC-BY-NC
#
# For more information, see: 
#
# https://raw.githubusercontent.com/legitbs/finals-2013/master/LICENSE
#

books = [
    "Absolution Gap by Alastair Reynolds",
    "Accelerando by Charles Stross",
    "Acidity by Nadeem F. Paracha",
    "Across the Universe by Beth Revis",
    "Adulthood Rites, Book Two of Xenogenesis Series by Octavia Butler",
    "After Doomsday by Poul Anderson",
    "The Age of the Pussyfoot, by Frederik Pohl",
    "Air by Geoff Ryman",
    "An Age by Brian Aldiss",
    "Alas, Babylon by Pat Frank",
    "Alastor Cluster series by Jack Vance",
    "The Alejandra Variations by Paul Cook",
    "The Algebraist by Iain M. Banks",
    "Alien Tongue by Stephen Leigh, Essay by Rudy Rucker",
    "Ancient Echoes by Robert Holdstock",
    "Andromeda by Ivan Efremov",
    "The Andromeda Strain by Michael Crichton",
    u"Andymon by Angela and Karlheinz Steinm\xc3\xbcller",
    "Anima by Marie Buchanan",
    "Animorphs by K. A. Applegate",
    "Annals of the Twenty-Ninth Century by Andrew Blair",
    "Anthem by Ayn Rand",
    "Anthony Villiers series by Alexei Panshin",
    "Ares Express by Ian McDonald",
    "The Artist of the Beautiful by Nathaniel Hawthorne",
    "As the Green Star Rises by Lin Carter",
    "Ascending by James Alan Gardner",
    "Asgard series by Brian Stableford",
    "The Atrocity Exhibition by J.G. Ballard",
    "Autumn Angels by Arthur Byron Cover",
    "Autour de la Lune by Jules Verne",
    "Awakeners series by Sheri S. Tepper",
    "Babel-17 by Samuel R. Delany",
    "The Balloon-Hoax by Edgar Allan Poe",
    "Barefoot in the Head by Brian Aldiss",
    "Battle Angel Alita by Yukito Kishiro",
    "Battlefield Earth by L. Ron Hubbard",
    "Becoming Alien by Rebecca Ore",
    "The Bell-Tower by Herman Melville",
    "Berserker by Fred Saberhagen",
    "Beyond Apollo by Barry N. Malzberg",
    "Bicentennial Man by Isaac Asimov",
    "The Bikers series by Alex R. Stuart",
    "Big Planet series by Jack Vance",
    "A Billion Days of Earth by Doris Piserchia",
    "Black by Ted Dekker",
    "Black Legion of Callisto by Lin Carter",
    "Blast Off at Woomera by Hugh Walters",
    "The Blind Worm by Brian Stableford",
    "Bloodchild and Other Stories by Octavia Butler",
    "Blood Music by Greg Bear",
    "The Blue Man by Kin Platt",
    "The Blue World by Jack Vance",
    "Borgel by Daniel Pinkwater",
    "Born With the Dead by Robert Silverberg",
    "Borrowed Tides by Paul Levinson",
    "Brave New World by Aldous Huxley",
    "Brasyl by Ian McDonald",
    "Breakfast of Champions (or Goodbye, Blue Monday!) by Kurt Vonnegut, Jr.",
    "Briah cycle by Gene Wolfe, several nested sub-series:",
    "The Book of the New Sun",
    "The Book of the Long Sun",
    "The Book of the Short Sun",
    "The Brick Moon by Edward Everett Hale",
    "Bug Jack Barron by Norman Spinrad",
    "The Butterfly Kid by Chester Anderson",
    "By the Light of the Green Star by Lin Carter",
    "Cadwal Chronicles series by Jack Vance",
    "Caesar's Column, by Ignatius Donnelly",
    "The Calcutta Chromosome by Amitav Ghosh",
    "Calling B for Butterfly by Louise Lawrence",
    "Camp Concentration by Thomas M. Disch",
    "A Canticle for Leibowitz by Walter M. Miller Jr.",
    "A Case of Conscience by James Blish",
    "The Caves of Steel by Isaac Asimov",
    "Cat's Cradle by Kurt Vonnegut",
    "Celestial Matters by Richard Garfinkle",
    "The Centauri Device by M. John Harrison",
    "Century Rain by Alastair Reynolds",
    "The Chalk Giants by Keith Roberts",
    "The Changeling by A. E. van Vogt",
    "Chanur series by C. J. Cherryh",
    "Chasm City by Alastair Reynolds",
    "Child of Fortune by Norman Spinrad",
    "Childhood's End by Arthur C. Clarke",
    "Children of Tomorrow by A. E. van Vogt",
    "Chromosome 6 by Robin Cook",
    "Chronocules by D. G. Compton",
    "The Chrysalids by John Wyndham",
    "Cinnabar by Edward Bryant",
    "Cirque by Terry Carr",
    "City by Clifford D. Simak",
    "The City and the Stars by Arthur C. Clarke",
    "City of Bones by Martha Wells",
    "City of Illusions by Ursula K. Le Guin",
    "Clans of the Alphane Moon by Philip K. Dick",
    "A Clockwork Orange by Anthony Burgess",
    "Clay's Ark by Octavia Butler",
    "The Complete Magnus Ridolph by Jack Vance",
    "Coalescent by Stephen Baxter"
]
