POLLS_TESTING_SEED= -710644949
AUTHOR_ID  = CROMU
SERVICE_ID = 00006
CFLAGS     = -O0 -g -Wall -Werror -Wno-overlength-strings -Wno-packed -mno-sse -fblocks
NO_STRIP   = 1

POLLS_RELEASE_MAX_DEPTH=20
POLLS_RELEASE_SEED=40

include /usr/share/cb-testing/cgc-cb.mk
