POLLS_RELEASE_SEED= -1563792830
POLLS_TESTING_SEED= -805162969
AUTHOR_ID  = NRFIN
SERVICE_ID = 00022
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
