POLLS_RELEASE_SEED= -563855678
POLLS_TESTING_SEED= -911784856
AUTHOR_ID  = NRFIN
SERVICE_ID = 00027
CFLAGS     = -O0 -g -Wall -Wextra -Wno-missing-field-initializers -Wno-sign-compare -mno-sse

include /usr/share/cb-testing/cgc-cb.mk
