POLLS_TESTING_SEED= -2107505200
AUTHOR_ID  = CROMU
SERVICE_ID = 00040
POLLS_RELEASE_COUNT=1000
POLLS_RELEASE_SEED=2555627392
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
include /usr/share/cb-testing/cgc-cb.mk
