POLLS_RELEASE_SEED= 1144235891
AUTHOR_ID  = KPRCA
SERVICE_ID = 00037
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_TESTING_COUNT = 1000
POLLS_TESTING_SEED = 90138345

include /usr/share/cb-testing/cgc-cb.mk
