POLLS_RELEASE_SEED= -1897487206
POLLS_TESTING_SEED= 2112505907
AUTHOR_ID  = YAN01
SERVICE_ID = 00007
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -fno-rtti

include /usr/share/cb-testing/cgc-cb.mk
