POLLS_RELEASE_SEED= 1240805680
AUTHOR_ID  = KPRCA
SERVICE_ID = 00032
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -msse
POLLS_TESTING_SEED = 843413816

include /usr/share/cb-testing/cgc-cb.mk
