POLLS_RELEASE_SEED= 646035515
POLLS_TESTING_SEED= -245294859
AUTHOR_ID  = CROMU
SERVICE_ID = 00039
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
