POLLS_RELEASE_SEED= -1486913362
POLLS_TESTING_SEED= -1225823284
AUTHOR_ID  = CROMU
SERVICE_ID = 00034
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
