POLLS_RELEASE_SEED= -1944875335
POLLS_TESTING_SEED= -1846630413
AUTHOR_ID  = CROMU
SERVICE_ID = 00009
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
