POLLS_TESTING_SEED= 1560403489
AUTHOR_ID  = KPRCA
SERVICE_ID = 00027
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 1189828196

include /usr/share/cb-testing/cgc-cb.mk
