//Autogenerated using calculateOffsets.py
#define EXPECTED_MEMSIZE 0xcafebaba
#define EXPECTED_TEXT_HASH 0xcafebabe
#define EXPECTED_DATA_HASH 0x6f981d5c
#define NUM_SKIPS 4
TextProtectSkip skips[NUM_SKIPS] = { {0x8048306,8}, {0x8048991,5}, {0x80489ac,8}, {0x80487b8,5},  };