AUTHOR_ID  = KPRCA
SERVICE_ID = 00102
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -include src/_defines.h
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1

include /usr/share/cb-testing/cgc-cb.mk
