POLLS_RELEASE_SEED= 172223516
POLLS_TESTING_SEED= -750311787
AUTHOR_ID  = NRFIN
SERVICE_ID = 00030
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
