POLLS_RELEASE_SEED= -1172814100
POLLS_TESTING_SEED= -1601446240
AUTHOR_ID  = NRFIN
SERVICE_ID = 00009
POLLS_RELEASE_COUNT = 1000
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
include /usr/share/cb-testing/cgc-cb.mk
