AUTHOR_ID  = NRFIN
SERVICE_ID = 00015

CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = -1766396818
POLLS_TESTING_SEED = -908939435

include /usr/share/cb-testing/cgc-cb.mk
