POLLS_RELEASE_SEED= -1916906245
AUTHOR_ID  = KPRCA
SERVICE_ID = 00038
CFLAGS     = -O2 -g -Werror -Wno-overlength-strings -Wno-packed -Wuninitialized
POLLS_TESTING_COUNT = 1000
POLLS_TESTING_SEED = 12873445

include /usr/share/cb-testing/cgc-cb.mk
