name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev libc6-dev-i386 g++-multilib ninja-build
          pip install --upgrade --user xlsxwriter pycrypto
      - name: build
        run: ./build.sh
