POLLS_TESTING_SEED= -460066697
AUTHOR_ID  = KPRCA
SERVICE_ID = 00054
CFLAGS     = -g -Wall -Wno-unused-function -fno-exceptions -fno-rtti -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -454027733

include /usr/share/cb-testing/cgc-cb.mk
